# Generated by Django 5.2.2 on 2025-06-05 13:23

import django.contrib.gis.db.models.fields
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('srid', models.IntegerField(default=4326)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fill_color', models.CharField(blank=True, help_text='Hanya untuk Polygon, hex dengan alpha (cth: #00FF0044)', max_length=9, null=True)),
                ('stroke_color', models.CharField(blank=True, help_text='Untuk Polygon/Line/Point, hex tanpa alpha (cth: #333333)', max_length=7, null=True)),
                ('stroke_width', models.FloatField(default=1.5, help_text='Untuk LineString dan Point outline')),
                ('marker_size', models.FloatField(default=6.0, help_text='Untuk Point (diameter marker)')),
                ('tags', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Area of Interest',
                'verbose_name_plural': 'Areas of Interest',
            },
        ),
    ]
