# Generated by Django 5.2.2 on 2025-06-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaofinterest',
            name='tags',
        ),
    ]
