# Generated by Django 5.2.2 on 2025-06-09 03:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_areaofinterest_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotspots',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('radius', models.FloatField()),
                ('long', models.FloatField()),
                ('lat', models.FloatField()),
                ('provinsi', models.CharField(max_length=255)),
                ('kabupaten', models.CharField(max_length=255)),
                ('kecamatan', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('times', models.TimeField()),
                ('conf', models.IntegerField()),
                ('sat', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
            ],
        ),
    ]
