# Generated by Django 5.2.2 on 2025-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_hotspots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofinterest',
            name='marker_size',
            field=models.FloatField(default=1.0, help_text='Untuk Point (diameter marker)'),
        ),
        migrations.AlterField(
            model_name='areaofinterest',
            name='stroke_width',
            field=models.FloatField(default=1.0, help_text='Untuk LineString dan Point outline'),
        ),
    ]
