# Generated by Django 5.2.2 on 2025-06-10 07:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_areaofinterest_marker_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotspots',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='DeforestationAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('event_id', models.CharField(max_length=250, unique=True)),
                ('alert_date', models.DateField(default=django.utils.timezone.now)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('confidence', models.IntegerField(blank=True, default=0, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deforestation_alerts', to='data.areaofinterest')),
            ],
            options={
                'ordering': ['-alert_date'],
                'indexes': [models.Index(fields=['alert_date'], name='data_defore_alert_d_ad47e8_idx'), models.Index(fields=['event_id'], name='data_defore_event_i_5d02b6_idx'), models.Index(fields=['company'], name='data_defore_company_fe0033_idx'), models.Index(fields=['geom'], name='data_defore_geom_f11fa6_idx')],
            },
        ),
    ]
