# Generated by Django 5.2.2 on 2025-06-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_hotspots_options_deforestationalerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deforestationalerts',
            name='key',
        ),
        migrations.AlterField(
            model_name='deforestationalerts',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
