# Generated by Django 5.2.2 on 2025-06-11 12:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_deforestationalerts_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deforestationalerts',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
