# Generated by Django 5.2.2 on 2025-06-16 02:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_alter_deforestationalerts_geom'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField(blank=True, help_text='Jarak dari hotspot ke batas AOI (meter)', null=True)),
                ('category', models.CharField(choices=[('AMAN', 'Aman'), ('PERHATIAN', 'Perhatian'), ('WASPADA', 'Waspada'), ('BAHAYA', 'Bahaya')], default='AMAN', max_length=10)),
                ('alert_date', models.DateField(default=django.utils.timezone.now)),
                ('confidence', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('area_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_alerts', to='data.areaofinterest')),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='data.hotspots')),
            ],
            options={
                'ordering': ['-alert_date'],
                'indexes': [models.Index(fields=['alert_date'], name='data_hotspo_alert_d_70b74f_idx'), models.Index(fields=['category'], name='data_hotspo_categor_41b8ca_idx'), models.Index(fields=['hotspot'], name='data_hotspo_hotspot_6f46d4_idx'), models.Index(fields=['area_of_interest'], name='data_hotspo_area_of_4fb48d_idx')],
                'unique_together': {('hotspot', 'area_of_interest')},
            },
        ),
    ]
