# Generated by Django 5.2.2 on 2025-06-20 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_hotspots_data_hotspo_date_c739e4_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Tidak Valid'), ('uncertain', 'Perlu Investigasi')], default='valid', help_text='Status hasil verifikasi di lapangan', max_length=20)),
                ('fire_evidence', models.BooleanField(default=False, help_text='Apakah ada bukti kebakaran di lapangan?')),
                ('photo_urls', models.JSONField(default=list, help_text='Daftar URL foto yang diambil saat verifikasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotspot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.hotspots')),
                ('verifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotspot_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
