# Generated by Django 5.2.2 on 2025-06-21 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_hotspotverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeforestationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_date', models.DateField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('false_alarm', 'False Alarm'), ('investigating', 'Sedang Diselidiki'), ('resolved', 'Selesai')], default='valid', max_length=50)),
                ('area_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='data.deforestationalerts')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deforestation_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verification_date'],
                'indexes': [models.Index(fields=['verification_date'], name='data_defore_verific_3921c7_idx'), models.Index(fields=['status'], name='data_defore_status_aaa67e_idx')],
            },
        ),
    ]
