# Generated by Django 5.2.2 on 2025-06-21 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_deforestationverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deforestationverification',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deforestation_verifications', to='data.deforestationalerts'),
        ),
        migrations.AlterField(
            model_name='deforestationverification',
            name='verifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifier_deforestation_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
