# Generated by Django 5.2.2 on 2025-06-21 00:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountnotificationsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountnotificationsetting',
            name='email_notifications',
        ),
        migrations.AddField(
            model_name='accountnotificationsetting',
            name='receivers_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, help_text='Daftar email tambahan yang akan menerima notifikasi', size=None),
        ),
        migrations.AddField(
            model_name='accountnotificationsetting',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='Opsional: URL untuk mengirim notifikasi via HTTP POST', null=True),
        ),
    ]
